name: "Manifest Source Storage"

on:
  push:
    branches:
    - master

jobs:
  enumerate:
    name: "Enumerate Manifests"
    runs-on: ubuntu-latest
    outputs:
      manifests: ${{ steps.enumerate.outputs.manifests }}
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2
    - name: "Enumerate Manifests"
      id: enumerate
      run: |
        MANIFESTS="$(make --silent msrc-list-diff "MSRC_TOKEN=${{ github.token }}")"
        echo "::set-output name=manifests::${MANIFESTS}"
    - name: "Print Manifest List"
      run: echo '${{ steps.enumerate.outputs.manifests }}' | jq .

  msrc:
    name: "Prefetch Sources"
    if: github.repository == 'osbuild/manifestdb'
    runs-on: ubuntu-latest
    needs: enumerate
    strategy:
      fail-fast: false
      matrix:
        manifest: ${{ fromJson(needs.enumerate.outputs.manifests) }}
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2
    - name: "Prefetch and Store Sources"
      uses: osbuild/containers/src/actions/ghci-osbuild@v1
      with:
        image: docker.pkg.github.com/osbuild/containers/ghci-manifestdb:v1
        run: |
          make msrc-push "MSRC_MANIFEST=${{ matrix.manifest }}"
