name: "Manifest Verification"

on: [pull_request, push]

jobs:
  mverify:
    name: "Manifest Check"
    runs-on: ubuntu-latest
    container: osbuilders/ghci-osbuild:v1
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2
    - name: "Run Check"
      run: |
        make mpp-verify
        make mtype-verify
        make mformat-verify
